# Generated by Django 3.0.7 on 2021-01-09 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('change_message', models.TextField()),
                ('action_flag', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('rut', models.IntegerField(blank=True, null=True)),
                ('dverificador', models.TextField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('apellido', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.TextField(blank=True, null=True)),
                ('correo', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('año_ingreso', models.IntegerField(blank=True, null=True)),
                ('año_salida', models.TextField(blank=True, null=True)),
                ('carrera', models.TextField(blank=True, null=True)),
                ('nombre_empresa', models.TextField(blank=True, null=True)),
                ('cargo', models.TextField(blank=True, null=True)),
                ('experiencia_laboral', models.TextField(blank=True, null=True)),
                ('ciudad_empresa', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.TextField(blank=True, null=True)),
                ('linkedin', models.TextField(blank=True, db_column='Linkedin', null=True)),
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='media')),
                ('nombre_foto', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'Lista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField()),
                ('dverificador', models.TextField()),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('fecha_nacimiento', models.TextField()),
                ('foto', models.ImageField(upload_to='media')),
                ('nombre_foto', models.CharField(blank=True, max_length=255)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('correo', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ajax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('search', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CsvUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('end_date', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('mobile_number', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(max_length=255)),
                ('location', models.TextField(max_length=255)),
                ('date', models.DateField(verbose_name='%m/%d/%Y')),
                ('created_at', models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S')),
                ('updated_at', models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialAcademico',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('año_ingreso', models.IntegerField(blank=True, null=True)),
                ('año_salida', models.IntegerField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('carrera', models.TextField(blank=True, null=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='crud.Persona')),
            ],
            options={
                'db_table': 'HistorialAcademico',
            },
        ),
        migrations.CreateModel(
            name='AreaDeDesarrollo',
            fields=[
                ('id_a_desarrollo', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.TextField(blank=True, null=True)),
                ('nombre_empresa', models.TextField(blank=True, null=True)),
                ('experiencia_laboral', models.TextField(blank=True, null=True)),
                ('ciudad', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.TextField(blank=True, null=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='studentst', to='crud.Persona')),
            ],
            options={
                'db_table': 'AreaDeDesarrollo',
            },
        ),
    ]
